const dateSelector = document.querySelector("#date-selector");
const classList = document.querySelector("#class-list");
const selectedDateLabel = document.querySelector("#selected-date-label");
const selectedDateCopy = document.querySelector("#selected-date-copy");
const bookingSelectionNote = document.querySelector("#booking-selection-note");
const bookingSessionInput = document.querySelector("#booking-session");
const bookingDateField = document.querySelector("#booking-date");
const bookingTimeField = document.querySelector("#booking-time");
const bookingNotesField = document.querySelector("#booking-notes");
const bookingRequestTypeInput = document.querySelector("#booking-request-type");
const bookingModal = document.querySelector("#booking-modal");
const bookingModalDialog = document.querySelector(".booking-modal-dialog");
const bookingOpenTriggers = document.querySelectorAll("[data-open-booking]");
const bookingCloseTriggers = document.querySelectorAll("[data-close-booking]");
const bookingNameField = document.querySelector("#booking-name");
const autoGeneratedSlotNotePattern = /^Requested for the .* class slot\.$/;

const dayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const monthNames = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

const createDailySchedule = (morningSpots, eveningSpots) => ({
  summary:
    "Two daily class slots are available at 10:30 AM and 6:00 PM. Choose Reformer or Mat Pilates in the booking popup.",
  classes: [
    {
      time: "10:30 AM",
      title: "Morning Class Slot",
      subtitle: "Choose Reformer or Mat Pilates when booking.",
      duration: "50 min",
      spots: morningSpots,
      typeOptions: "Reformer or Mat Pilates",
    },
    {
      time: "6:00 PM",
      title: "Evening Class Slot",
      subtitle: "Choose Reformer or Mat Pilates when booking.",
      duration: "50 min",
      spots: eveningSpots,
      typeOptions: "Reformer or Mat Pilates",
    },
  ],
});

const weeklySchedule = [
  createDailySchedule(4, 5),
  createDailySchedule(3, 4),
  createDailySchedule(5, 3),
  createDailySchedule(4, 4),
  createDailySchedule(2, 5),
  createDailySchedule(5, 4),
  createDailySchedule(4, 3),
];

const formatIsoDate = (date) => {
  const adjusted = new Date(date);
  adjusted.setMinutes(adjusted.getMinutes() - adjusted.getTimezoneOffset());
  return adjusted.toISOString().split("T")[0];
};

const dates = Array.from({ length: 7 }, (_, index) => {
  const date = new Date();
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() + index);
  return date;
});

let selectedDateIndex = 0;
const defaultBookingSelectionNote = bookingSelectionNote?.textContent.trim() || "";
let lastBookingTrigger = null;

const openBookingModal = (selectedDate = dates[selectedDateIndex]) => {
  if (!bookingModal) {
    return;
  }

  if (bookingDateField && !bookingDateField.value) {
    bookingDateField.value = formatIsoDate(selectedDate);
  }

  if (bookingRequestTypeInput && !bookingRequestTypeInput.value) {
    bookingRequestTypeInput.value = "booking";
  }

  bookingModal.hidden = false;
  document.body.classList.add("modal-open");

  window.requestAnimationFrame(() => {
    (bookingNameField || bookingSessionInput || bookingModalDialog)?.focus?.();
  });
};

const closeBookingModal = () => {
  if (!bookingModal) {
    return;
  }

  bookingModal.hidden = true;
  document.body.classList.remove("modal-open");
  lastBookingTrigger?.focus?.();
};

const buildDateButton = (date, index) => {
  const button = document.createElement("button");
  button.type = "button";
  button.className = "date-chip";
  button.dataset.index = String(index);

  if (index === selectedDateIndex) {
    button.classList.add("is-active");
  }

  button.innerHTML = `
    <span class="date-chip-label">${index === 0 ? "Today" : dayNames[date.getDay()]}</span>
    <strong>${String(date.getDate()).padStart(2, "0")}</strong>
    <span class="date-chip-meta">${monthNames[date.getMonth()]}</span>
  `;

  button.addEventListener("click", () => {
    selectedDateIndex = index;
    renderDateButtons();
    renderSchedule();
  });

  return button;
};

const renderDateButtons = () => {
  if (!dateSelector) {
    return;
  }

  dateSelector.innerHTML = "";
  dates.forEach((date, index) => {
    dateSelector.append(buildDateButton(date, index));
  });
};

const resetBookingSelection = (selectedDate = dates[selectedDateIndex]) => {
  if (bookingSessionInput) {
    bookingSessionInput.value = "";
  }

  if (bookingDateField) {
    bookingDateField.value = formatIsoDate(selectedDate);
  }

  if (bookingTimeField) {
    bookingTimeField.value = "";
  }

  if (bookingRequestTypeInput) {
    bookingRequestTypeInput.value = "booking";
  }

  if (bookingSelectionNote) {
    bookingSelectionNote.textContent = defaultBookingSelectionNote;
  }
};

const prefillBookingForm = (bookingClass, date) => {
  if (document.activeElement instanceof HTMLElement) {
    lastBookingTrigger = document.activeElement;
  }

  if (bookingSessionInput) {
    bookingSessionInput.value = "";
  }

  if (bookingDateField) {
    bookingDateField.value = formatIsoDate(date);
  }

  if (bookingTimeField) {
    bookingTimeField.value = bookingClass.time;
  }

  if (bookingRequestTypeInput) {
    bookingRequestTypeInput.value = bookingClass.spots === 0 ? "waitlist" : "booking";
  }

  if (
    bookingNotesField &&
    (!bookingNotesField.value.trim() ||
      autoGeneratedSlotNotePattern.test(bookingNotesField.value.trim()))
  ) {
    bookingNotesField.value = `Requested for the ${bookingClass.time} class slot.`;
  }

  if (bookingSelectionNote) {
    const action = bookingClass.spots === 0 ? "waitlist request" : "booking request";
    bookingSelectionNote.textContent = `${bookingClass.time} has been selected for your ${action}. Choose Reformer or Mat Pilates to complete it.`;
  }

  openBookingModal(date);
};

const buildClassCard = (bookingClass, date) => {
  const article = document.createElement("article");
  article.className = "live-class-card";

  const buttonLabel = bookingClass.spots === 0 ? "Waitlist" : "Book";

  article.innerHTML = `
    <div class="live-class-top">
      <div>
        <p class="live-class-meta">${bookingClass.time} · ${bookingClass.duration}</p>
        <h3 class="live-class-title">${bookingClass.title}</h3>
        <p class="live-class-instructor">${bookingClass.subtitle}</p>
      </div>
      <button class="class-book-button ${bookingClass.spots === 0 ? "is-waitlist" : ""}" type="button">
        ${buttonLabel}
      </button>
    </div>
    <div class="live-class-tags">
      <span class="intensity-tag">${bookingClass.typeOptions}</span>
      <span class="spots-tag">${bookingClass.spots === 0 ? "Class full" : `${bookingClass.spots} ${bookingClass.spots === 1 ? "spot" : "spots"} left`}</span>
    </div>
  `;

  article
    .querySelector(".class-book-button")
    ?.addEventListener("click", () => prefillBookingForm(bookingClass, date));

  return article;
};

const renderSchedule = () => {
  if (!classList) {
    return;
  }

  const activeDate = dates[selectedDateIndex];
  const daySchedule = weeklySchedule[selectedDateIndex] || weeklySchedule[0];

  if (selectedDateLabel) {
    selectedDateLabel.textContent =
      selectedDateIndex === 0
        ? "Today at MUSE"
        : `${dayNames[activeDate.getDay()]} ${activeDate.getDate()} ${monthNames[activeDate.getMonth()]}`;
  }

  if (selectedDateCopy) {
    selectedDateCopy.textContent = daySchedule.summary;
  }

  if (bookingDateField && !bookingDateField.value) {
    bookingDateField.value = formatIsoDate(activeDate);
  }

  classList.innerHTML = "";
  daySchedule.classes.forEach((bookingClass) => {
    classList.append(buildClassCard(bookingClass, activeDate));
  });
};

renderDateButtons();
renderSchedule();

bookingOpenTriggers.forEach((trigger) => {
  trigger.addEventListener("click", (event) => {
    event.preventDefault();
    lastBookingTrigger = trigger;
    resetBookingSelection();
    openBookingModal();
  });
});

bookingCloseTriggers.forEach((trigger) => {
  trigger.addEventListener("click", () => closeBookingModal());
});

window.addEventListener("keydown", (event) => {
  if (event.key === "Escape" && bookingModal && !bookingModal.hidden) {
    closeBookingModal();
  }
});
